version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sky_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
